[project]
name = "rag-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "ipykernel>=6.30.1",
    "ollama>=0.6.0",
    "pymupdf>=1.26.5",
]
